version: '3'
services:
  db:
    container_name: hiik_rabota
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DATABASE=api